<?php

namespace AppBundle\Repository;

/**
 * NodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySeqGreaterThan($seq){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT n
                 FROM AppBundle:Node n
                 WHERE n.seq > ' . $seq
            )
            ->getResult();
    }

    public function findNameBySeqGreaterThan($seq){
        $arNameArray = $this->getEntityManager()
            ->createQuery(
                'SELECT n.name
                 FROM AppBundle:Node n
                 WHERE n.seq > ' . $seq
            )
            ->getArrayResult();

        $arNames = array();
        foreach ($arNameArray as $name) {
            array_push($arNames, $name['name']);
        }

        return $arNames;
    }

}
