<?php

namespace AppBundle\Repository;

/**
 * NodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySeqGreaterThan($seq){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT n
                 FROM AppBundle:Node n
                 WHERE n.seq > ' . $seq
            )
            ->getResult();
    }
}
