<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Sequence;

/**
 * SequenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SequenceRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $seqName
     * @return int
     */
    public function getLastSeq($seqName){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s
                 FROM AppBundle:Sequence s
                 WHERE s.sequence = :seqName'
            )
            ->setParameter('seqName', $seqName)
            ->getResult()[0]->getValue() -1 ;
    }
}
