<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Sequence;

/**
 * SequenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SequenceRepository extends \Doctrine\ORM\EntityRepository
{

}
